### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by yiluheihei** [yiluheihei/microbiomeMarker#3]
### methods

- [x]  number of markers, `nmarker` generic: `nmarker(phyloseq)`, `nmarker(marker_table)`
- [x]  number of classes used for biomarker discovery, `nclass` generic: `nclass(phyloseq)`, `nclass(marker_table)`
- [x] number of taxa and samples, exported from phyloseq
- [x] `taxa_names` and  `sample_names` exported from phyloseq

### classical statistical analysis (stamp)

- [x]  `test_two_groups()`: test between two groups

    - [x]  t test, welch t test,  wilcoxon test, whether correction (e.g. fdr) or not
    - [x] confidence interval, welch's inverted
    - [x]  effect size, difference of proportions and ratio of proportions

### normalization

- [x] normalization method
- [x] support other normalization for lefse analysis (unsummarized data)
- [x] `transform` and `normalization` argument
- [x] `norm_rle()` (DESeq2), add para `type`, see `DESeq2::estimateSizeFactors()`.
- [x] add para `norm` for DESeq2, metagenomeSeq, ...
- [x] `norm_value()` to `norm_cpm()`, the correponding normalization method is `million`.

### diff analysis

- [x] supervised learning
- [x] limma 
- [x] add new para `summarize` to specify whether summarize the taxa or not, if not add a new para `tax_level` to specify  the level of taxa for differential analysis.

### visualization

- [x] cladogram visualization for all method
- [x] `dotplot()` and `barplot()`
- [x] effect size visualization (bar and dot plot) (referred in MicrobiotaProcess), boxplot (a ci plot for post-hoc test result)
- [x] extra visualization: heat map and heatmap tree
- [ ] qiime ma plots, see [here](http://qiime.org/scripts/differential_abundance.html), para `DESeq2_diagnostic_plots`
- [x] update `plot_ef()` to support all diffential methods

### Others 

- [x] a unified interface (function) for all different analysis methods, e.g. `find_markers(ps, method = c("lefse", "wilcon", "t", "edgeR", "metagenomeSeq", "DESeq2", ...), ...)` 
- [x] data importing: `import_biom`, `import_mothur`, `import_qiime`, `import_qiim2`, `import_dada2`, phyloseq and MicrobiotaProcess import function.
- [ ] [checkdots](https://github.com/satijalab/seurat/blob/master/R/utilities.R#L1604)
- [x] not support summarized data, since it is just for testing whether the lefse method in our package is in accordance with lefse python script.

## update

- [x] Since there may be too many markers, it is neccessary to add a para `number_feature` in `plot_cladogram()` and `lefse_bar()`, default `[15]`, indicating plot the top 15 markers.  
- [x]   by setting `clade_label_level` in `plot_cladogram()` , if there is no  marker in the clade, raise  an error "no marker in the cladogram", and if there is no marker in the side, raise a warning "no marker in the side".
- [x]  deseq2, edger, metagenomeSeq for multiple groups
  - [How to perform multiple comparisons using edgeR?](https://www.biostars.org/p/382480/)
  - [DESeq2- R commands for multiple groups](https://www.biostars.org/p/295496/)
  - metagenomeSeq, package vignette
- [x] merge `test_two_groups` and `test_multiple_groups` to one `run_simple_test` (run simple statistical tests).

## Q

- how to preprocess the unclassified taxa, remove or not (in the current version, the unclassified  otus is not removed.
- merge the unclassified taxa belonged to the same upper level or not (in the current version, the unclassified otus are merged).
- method for p correction in aldex is "BH", users can not set this para manually
-  Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq' Also defined by ‘tidytree’?
-  contrast
- var of ef_*
- The software was designed to determine features (be it Operational Taxanomic Unit (OTU), species, etc.) that are differentially abundant between two or more groups of multiple samples. (metagenomeSeq vignette)

**Comment by yiluheihei** [comment]
statistic analysis, reference [stamp](https://beikolab.cs.dal.ca/software/STAMP)

- [ ]  `test_two_groups()`: test between two groups

    - [ ]  t test, welch t test,  wilcoxon test, whether correction (e.g. fdr) or not
    - [ ] confidence interval, welch's inverted
    - [ ]  effect size, difference of proportions and ratio of proportions

**Comment by yiluheihei** [comment]
- [ ]  generic function `plot.postHocTest()`,  use `facet_wrap()` to plot multiple features
